version: "3.8"

services:
  web:
    build: ./app
    container_name: web
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/restproject
    depends_on:
      - db


  db:
    restart: always
    image: postgres:15-alpine
    container_name: db01
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=restproject
    expose:
      - 5432


volumes:
  postgres_data:
    name: postgres
